INSERT INTO city (id, name) VALUES
(1, 'Sarajevo'),
(2, 'Zenica'),
(3, 'Travnik'),
(4, 'Fojnica'),
(5, 'Novi Travnik'),
(6, 'Vitez'),
(7, 'Bihać'),
(8, 'Breza'),
(9, 'Tuzla'),
(10, 'Mostar'),
(11, 'Maglaj'),
(12, 'Visoko'),
(13, 'Srebrenica'),
(14, 'Banja Luka'),
(15, 'Bijeljina'),
(16, 'Prijedor'),
(17, 'Trebinje'),
(18, 'Zvornik'),
(19, 'Višegrad'),
(20, 'Cazin'),
(21, 'Jajce'),
(22, 'Visoko'),
(23, 'Kakanj'),
(24, 'Gradačac'),
(25, 'Žepče');
